function build_public_field_figure(inputCsv, outputPng)
%BUILD_PUBLIC_FIELD_FIGURE Create the privacy-reviewed public PM2.5 figure.
%   The input may contain site-level columns, but this figure intentionally
%   plots only regional aggregates and never displays station names,
%   distances, coordinates, or device identifiers.

arguments
    inputCsv (1, 1) string
    outputPng (1, 1) string
end

required = [
    "timestamp_utc"
    "sensor_pm25_mean"
    "airnow_regional_mean_pm2_5"
    "purpleair_raw_median_pm2_5"
    "purpleair_epa_median_pm2_5"
];

data = readtable(inputCsv, "VariableNamingRule", "preserve");
missing = setdiff(required, string(data.Properties.VariableNames));
if ~isempty(missing)
    error("PublicFigure:MissingColumns", ...
        "Missing required columns: %s", strjoin(missing, ", "));
end

timeUtc = datetime(data.timestamp_utc, ...
    "InputFormat", "yyyy-MM-dd'T'HH:mm:ss'Z'", ...
    "TimeZone", "UTC");
timeLocal = timeUtc;
timeLocal.TimeZone = "America/New_York";

sensor = double(data.sensor_pm25_mean);
airnow = double(data.airnow_regional_mean_pm2_5);
purpleairRaw = double(data.purpleair_raw_median_pm2_5);
purpleairCorrected = double(data.purpleair_epa_median_pm2_5);

figureHandle = figure( ...
    "Color", "white", ...
    "Position", [100 100 1500 760], ...
    "Visible", "off");
cleanup = onCleanup(@() close(figureHandle)); %#ok<NASGU>

axesHandle = axes(figureHandle, ...
    "Position", [0.08 0.17 0.89 0.68], ...
    "FontName", "Arial", ...
    "FontSize", 13, ...
    "LineWidth", 1, ...
    "Box", "off", ...
    "XGrid", "on", ...
    "YGrid", "on", ...
    "GridAlpha", 0.16, ...
    "MinorGridAlpha", 0.08, ...
    "Color", "white");
hold(axesHandle, "on");

sensorLine = plot(axesHandle, timeLocal, sensor, ...
    "Color", [0.07 0.10 0.15], "LineWidth", 2.6);
airnowLine = plot(axesHandle, timeLocal, airnow, ...
    "Color", [0.15 0.39 0.92], "LineWidth", 2.1);
rawLine = plot(axesHandle, timeLocal, purpleairRaw, ...
    "Color", [0.92 0.35 0.05], "LineWidth", 2.1);
correctedLine = plot(axesHandle, timeLocal, purpleairCorrected, ...
    "Color", [0.08 0.50 0.24], "LineWidth", 2.1);

xlim(axesHandle, [min(timeLocal) max(timeLocal)]);
ylim(axesHandle, [0 1.08 * max([sensor; airnow; purpleairRaw; purpleairCorrected], [], "omitnan")]);
xtickformat(axesHandle, "MMM dd");
ylabel(axesHandle, "PM_{2.5} (micrograms m^{-3})", "Interpreter", "tex");
xlabel(axesHandle, "Local time (EDT)");

title(axesHandle, ...
    "PM_{2.5} time series: Atlanta-area SPS30 and regional comparisons", ...
    "FontName", "Arial", "FontSize", 21, "FontWeight", "bold", ...
    "Interpreter", "tex");
subtitle(axesHandle, ...
    "Hourly means | 18 Jul-9 Aug 2026 | regional aggregate comparison", ...
    "FontName", "Arial", "FontSize", 13, "Color", [0.35 0.40 0.47]);

legend(axesHandle, ...
    [sensorLine airnowLine rawLine correctedLine], ...
    ["SPS30 research node", "AirNow regional mean", ...
     "PurpleAir CF=1 regional median", ...
     "PurpleAir EPA-corrected regional median"], ...
    "Location", "northoutside", ...
    "Orientation", "horizontal", ...
    "NumColumns", 2, ...
    "Box", "off", ...
    "FontName", "Arial", ...
    "FontSize", 12);

annotation(figureHandle, "textbox", [0.08 0.025 0.89 0.07], ...
    "String", [
        "PurpleAir lines are regional medians after channel QA. " + ...
        "Station names, distances, and exact deployment location are intentionally omitted." newline + ...
        "Non-collocated preliminary comparison; not a calibration or regulatory validation."
    ], ...
    "FitBoxToText", "off", ...
    "EdgeColor", "none", ...
    "Color", [0.35 0.40 0.47], ...
    "FontName", "Arial", ...
    "FontSize", 10.5, ...
    "VerticalAlignment", "middle");

outputFolder = fileparts(outputPng);
if strlength(outputFolder) > 0 && ~isfolder(outputFolder)
    mkdir(outputFolder);
end
exportgraphics(figureHandle, outputPng, "Resolution", 180);
end
